### ISSUE TITLE
Changing objID dtype to np.str

### ISSUE THREAD

**Issue by alex-delavega** [jacopo-chevallard/PyP-BEAGLE#24]
Hi Emma and Jacopo,

This came up earlier in March but I forgot to submit an issue until now. 

I'd like to post-process BEAGLE fits to regions within galaxies, so my object IDs are usually written as `galaxy-id_region-id`, so the `dtype` for the ObjID would be `np.str`. So far, I've been creating triangle and marginal photometry plots and summary catalogues by launching `test_photometry.py`. Emma changed some lines so that the `objID` used by PyP-BEAGLE would be a string, namely (back in v0.3.0, I think):

in `beagle_posterior_predictive_checks.py`, line 234:
    changing `dtype` to `np.str`

and

in `beagle_utils.py`, lines 387 to 407:
    changing `dtype` to `np.str`. 

For the latest release (v0.4.4.), I made the same change above for the latest version of `beagle_posterior_predictive_checks.py`, and launching `test_photometry.py`works fine until having to compute the residual photometry (the last two lines), which produces this error:

```
Traceback (most recent call last):
  File "test_photometry.py", line 149, in <module>
    my_photometry.summary_catalogue, my_photometry.filters)
  File "../PyP-BEAGLE/beagle_residual_photometry.py", line 103, in compute
    kde_pdf = WeightedKDE.gaussian_kde(residual, weights = 1./residualErr)
  File "../PyP-BEAGLE/dependencies/WeightedKDE.py", line 145, in __init__
    raise ValueError("`dataset` input should have multiple elements.")
ValueError: `dataset` input should have multiple elements.
```

Would it be possible to modify the objID `dtype` so that string object IDs can be used in PyP-BEAGLE? Thanks!

**Comment by jacopo-chevallard** [comment]
this should have been solved some time ago already, closing
