### ISSUE TITLE
text.latex.preview error on fresh install

### ISSUE THREAD

**Issue by ImaanBontle** [jacopo-chevallard/PyP-BEAGLE#48]
Hi Jacopo,

I am having some issues getting PyP-BEAGLE running on a fresh BEAGLE install.

I have followed the wiki instructions as closely as possible (setting up BEAGLE environment variables and copying the matplotlib config file), but I am still getting 'text.latex.preview' errors (full error below).

This happens for me with both marginal and triangle plots, as well as summary files. All of this while running in python 3.8 on MacOS Big Sur 11.6. 

Any idea what could be causing the issue?

> Traceback (most recent call last):
>   File "/Library/Python/3.8/site-packages/matplotlib/\_\_init\_\_.py", line 644, in \_\_setitem\_\_
>     cval = self.validate\[key\]\(val\)
> KeyError: 'text.latex.preview'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/pyp_beagle", line 8, in <module>
>     sys.exit(main())
>   File "/Library/Python/3.8/site-packages/pyp_beagle/command_line.py", line 53, in main
>     configure_matplotlib()
>   File "/Library/Python/3.8/site-packages/pyp_beagle/beagle_utils.py", line 126, in configure_matplotlib
>     mpl.rcParams['text.latex.preview'] = True
>   File "/Library/Python/3.8/site-packages/matplotlib/\_\_init\_\_.py", line 649, in \_\_setitem\_\_
>     raise KeyError(
> KeyError: 'text.latex.preview is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'

**Comment by ImaanBontle** [comment]
Hi Jacopo

It seems that PyP-BEAGLE calls on some commands which are now deprecated (one of which is text.latex.preview). I managed to bypass the issue (at least temporarily) by reverting to an older version of matplotlib (3.4.3 seems sufficient).

Are there plans to update PyP-BEAGLE to current versions of matplotlib?

**Comment by jacopo-chevallard** [comment]
same for this @ImaanBontle, version 0.9.3 should fix this, can you, please, confirm when you have a chance?

**Comment by ImaanBontle** [comment]
@jacopo-chevallard Yep, everything works fine now with an updated matplotlib!
