### ISSUE TITLE
goodness of fit in beagle summary catalogue

### ISSUE THREAD

**Issue by eclake** [jacopo-chevallard/PyP-BEAGLE#49]
Would be great to have the minimum chi2 in the beagle summary catalogue output

**Comment by eclake** [comment]
We currently have no goodness-of-fit statistics, but it's necessary to tell what fits to trust and what not to trust.  I think it's fine as long as minimum_chi2 is clearly explained.

**Comment by jacopo-chevallard** [comment]
ok I see, this is because you never managed to use the posterior predictive checks, am I correct? In this case I'd rather make those more user-friendly

**Comment by jacopo-chevallard** [comment]
@eclake cc @scharlot I added a few things in the summary catalogue, namely the probability, likelihood and chi-square corresponding to the MAP solution. I also added the option to "flatten" the summary catalogue to only have columns containing scalar values --> it means that each *_68.00 or *_95.00 columns are replaces by *_68.00_low and *_68.00_up columns

**Comment by jacopo-chevallard** [comment]
@eclake I updated the README, see https://github.com/jacopo-chevallard/PyP-BEAGLE/blob/master/README.md#description
