### ISSUE TITLE
Astropy 'clobber' argument not recognised, summary catalogues

### ISSUE THREAD

**Issue by ImaanBontle** [jacopo-chevallard/PyP-BEAGLE#50]
Hi Jacopo,

It appears that 'clobber' has been deprecated from AstroPy v5.1, preventing the computation of summary catalogues. 

I am afraid I can't provide a copy of the error message, but it should be relatively easy to reproduce.

I believe the problem lies in the *.writeto() method of astropy.io.fits (see [changelog](https://docs.astropy.org/en/stable/changelog.html#id4)), and that fixing it should be as straightforward as changing "clobber=overwrite" to "overwrite=true", or something to that effect.

I am not sure how backwards-compatible this change is. Rolling back to v5.0 is a temporary fix for now.

**Comment by fdeugenio** [comment]
Hi Jacopo and Imaan,

the keyword 'clobber' is replaced by 'overwrite'. So a reasonable 
substitution* would be:

replace 'clobber=' with 'overwrite='

Cheers,

Francesco

*Assuming you don't use 'clobber' elsewhere in the code!

PS. If you pass keywords as dictionaries, then also replace instances of 
'clobber': and "clobber":
