### ISSUE TITLE
latex - python incompatibility

### ISSUE THREAD

**Issue by ahwofford** [jacopo-chevallard/PyP-BEAGLE#8]
My python version is: Python 2.7.11 :: Anaconda 4.0.0 (x86_64)

I am having trouble with latex and pyp-beagle. Do I need a special package? For instance, if in the .json file I use:

"tauv_eff": {
 "range": [0.001, 5.0],
 "label": "$\log \hat{\tau}_V$",
 "log" : true
},

I get:

$$\log \hat{\tau}_\V$$
^
Expected end of text (at char 0), (line:1, col:1)

**Comment by wudlike** [comment]
I had the same problem and spent a lot of time to fix it. I tried to implement a python file which contains latex symbol like \alpha, \beta (i have tried to write as: label = '$\alpha$', label = r'$\alpha$', label = '\alpha'),  but all of them do not work, and i got error
ValueError: 
$$\alpha_s$$
^
Expected end of text (at char 0), (line:1, col:1)

I finally fixed error by writing label as : '\\alpha'.
hope helpful to all of you
